version: "3"
services:
  go-dice-generator:
    build: .
    ports:
      - 8080:8080

  swagger:
    image: swaggerapi/swagger-ui:v3.39.0
    environment:
      SWAGGER_JSON: /etc/go-dice-generator/swagger.json
    ports:
      - 9090:8080
    volumes:
      - ./docs:/etc/go-dice-generator
