version: "3"
services:
  go-dice-backend:
    build: .
    ports:
      - 8080:8080

  swagger:
    image: swaggerapi/swagger-ui:v3.52.5
    environment:
      SWAGGER_JSON: /etc/go-dice-backend/swagger.json
    ports:
      - 9090:8080
    volumes:
      - ./docs:/etc/go-dice-backend
